DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS search;
DROP TABLE IF EXISTS result;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE search (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  organism TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result_count INTEGER,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE result (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  search_id INTEGER NOT NULL,
  accession TEXT NOT NULL,
  title TEXT NOT NULL,
  bp_length INTEGER,
  updated TEXT,
  ambiguity_percentage REAL,
  FOREIGN KEY (search_id) REFERENCES search (id)
);